const assert=require('node:assert/strict'),fs=require('fs');
const nodes=JSON.parse(fs.readFileSync('src/workflows/xdx_supplier_core_20260924.wf')).specification.dataPipeline.pipelineNodes;
for(const n of nodes.filter(n=>n.type==='CODE'))new Function('$context',n.metadata.sourceCode);
const run=(code,c)=>new Function('$context',nodes.find(n=>n.code===code).metadata.sourceCode)(c);
const parent='300000333814409',address='300000333814416',bu=300000046987012;
const payload={SupplierSite:'XDX "Site" \\ Test',ProcurementBUId:bu,SupplierAddressName:'XDX Core Address 20260924',SitePurposePurchasingFlag:true};
function ctx(message,intent,patch={},state={},supplierId=''){return {$app:{$OraMessageHint:'Query'},$system:{$inputMessage:message},$workflow:{$jobId:'site-request'},$variables:{siteState:structuredClone(state),readState:{}},$nodes:{EXTRACT_READ:{$output:{intent,sitePatch:patch,supplierId,limit:5,offset:0}}}};}
function refs(state,op='review',overrides={}){const c=ctx('','',{},state);c.$nodes.CHECK_SITE_PARENT={$output:{result:{requestedOperation:op}}};c.$nodes.FETCH_SITE_ADDRESS_REFERENCE={$output:{items:[{SupplierAddressId:address,AddressName:payload.SupplierAddressName,AddressPurposeOrderingFlag:true,Status:'ACTIVE'}],count:1,hasMore:false,offset:0}};c.$nodes.FETCH_SITE_BU_REFERENCE={$output:{items:[{ProcurementBUId:bu,ProcurementBU:'US1 Business Unit',AgentAction:'A'},{ProcurementBUId:bu,ProcurementBU:'US1 Business Unit',AgentAction:'B'}],count:2,hasMore:false,offset:0}};Object.assign(c.$nodes,overrides);return c;}
let c=ctx('prepare site','prepare_site',payload,{},parent),p=run('PREPARE_SITE',c),s=p.state;assert.equal(p.route,'parent');c.$variables.siteState=s;c.$nodes.PREPARE_SITE={$output:{result:p}};c.$nodes.FETCH_SITE_PARENT={$output:{SupplierId:'999',Supplier:'Wrong'}};assert.equal(run('CHECK_SITE_PARENT',c).operation,'display');
c.$nodes.FETCH_SITE_PARENT.$output={SupplierId:parent,Supplier:'XDX Parent',BusinessRelationship:'Spend Authorized'};s=run('CHECK_SITE_PARENT',c).state;assert.equal(run('CHECK_SITE_PARENT',c).operation,'references');
s=run('CHECK_SITE_REFERENCES',refs(s,'draft')).state;assert.equal(s.tx.referenceAddressId,address);assert.equal(s.tx.buName,'US1 Business Unit');
s=run('PREPARE_SITE',ctx('Change site name','edit_site',{SupplierSite:'XDX Revised Site'},s)).state;assert.equal(s.tx.revision,2);assert.equal(s.tx.payload.ProcurementBUId,bu);assert.equal(s.tx.payload.SupplierAddressName,payload.SupplierAddressName);
p=run('PREPARE_SITE',ctx('review site','review_site',{},s));assert.equal(p.operation,'review');s=run('CHECK_SITE_REFERENCES',refs(s)).state;assert(s.tx.reviewedPayload.includes(address));s=run('PREPARE_SITE',ctx('approve site site-request revision 2','approve_site',{},s)).state;assert(s.tx.approval);
assert.equal(run('PREPARE_SITE',ctx('create site site-request revision 1','create_site',{},s)).route,'display');assert.equal(run('PREPARE_SITE',ctx('create site site-request revision 2','create_site',{},s)).operation,'preflight');
const change=run('PREPARE_SITE',ctx('Change BU','edit_site',{ProcurementBUId:bu+1},s));assert.equal(change.state.tx.approval,null);
const changedParent=run('PREPARE_SITE',ctx('Change parent','edit_site',{},s,'999'));assert.equal(changedParent.state.tx.approval,null);assert.equal(changedParent.route,'parent');
const changedAddress=refs(s,'preflight');changedAddress.$nodes.FETCH_SITE_ADDRESS_REFERENCE.$output.items[0].SupplierAddressId='999';assert.equal(run('CHECK_SITE_REFERENCES',changedAddress).next,'display');assert.equal(run('CHECK_SITE_REFERENCES',changedAddress).state.tx.approval,null);
for(const kind of ['incomplete','mismatch','unknown','nonordering','wrongaddress']){const bad=refs(s,'preflight');if(kind==='incomplete')bad.$nodes.FETCH_SITE_BU_REFERENCE.$output.hasMore=true;if(kind==='mismatch')bad.$nodes.FETCH_SITE_BU_REFERENCE.$output.items[1].ProcurementBU='Other';if(kind==='unknown')bad.$variables.siteState.tx.payload.ProcurementBUId=123;if(kind==='nonordering')bad.$nodes.FETCH_SITE_ADDRESS_REFERENCE.$output.items[0].AddressPurposeOrderingFlag=false;if(kind==='wrongaddress')bad.$nodes.FETCH_SITE_ADDRESS_REFERENCE.$output.items[0].AddressName='Wrong';assert.equal(run('CHECK_SITE_REFERENCES',bad).next,'display',kind);assert.equal(run('CHECK_SITE_REFERENCES',bad).state.tx.approval,null);}
s=run('CHECK_SITE_REFERENCES',refs(s,'preflight')).state;c=ctx('','',{},s);c.$nodes.CHECK_SITE_DUPLICATE={$output:{items:[{SupplierSiteId:'999',SupplierSite:'XDX Revised Site'}],count:1,hasMore:false,offset:0}};assert.equal(run('AUTHORIZE_SITE_WRITE',c).next,'display');c.$nodes.CHECK_SITE_DUPLICATE.$output={items:[],count:0,hasMore:false,offset:0};p=run('AUTHORIZE_SITE_WRITE',c);assert.equal(p.next,'write');assert.equal(p.state.tx.status,'pending');assert.equal(p.state.tx.approval,null);
const f=JSON.parse(fs.readFileSync('src/businessObjects/xdx_supplier_core_data_20260924.bo')).objectProperties.tools.find(x=>x.name==='create_suppliers_sites');const body=JSON.parse(f.bodyTemplate.replace(/\{([A-Za-z][A-Za-z0-9]*)\}/g,(_,k)=>String(p.escaped[k])));assert.deepEqual(body,s.tx.payload);assert.equal(typeof body.ProcurementBUId,'number');assert.equal(typeof body.SitePurposePurchasingFlag,'boolean');assert(!('SupplierSiteId' in body));
s=p.state;assert.equal(run('PREPARE_SITE',ctx('prepare','prepare_site',payload,s,parent)).route,'display');c=ctx('','',{},s);c.$nodes.CREATE_SITE={$output:{}};assert.equal(run('CAPTURE_SITE_CREATE',c).valid,false);c.$nodes.CREATE_SITE.$output={SupplierSiteId:'300000999'};s=run('CAPTURE_SITE_CREATE',c).state;
c=ctx('','',{},s);c.$nodes.GET_CREATED_SITE={$output:{...s.tx.payload,SupplierSiteId:'300000999',SupplierAddressId:address,ProcurementBU:'US1 Business Unit'}};const accepted=run('VERIFY_SITE_CREATE',c).state;assert.equal(accepted.tx.status,'verified');assert(run('PREPARE_SITE',ctx('create site site-request revision 2','create_site',{},accepted)).state.widget.includes('No second POST'));
for(const [k,v]of [['SupplierAddressId','999'],['ProcurementBU','Other'],['SitePurposePurchasingFlag',false]]){c=ctx('','',{},s);c.$nodes.GET_CREATED_SITE={$output:{...s.tx.payload,SupplierSiteId:'300000999',SupplierAddressId:address,ProcurementBU:'US1 Business Unit',[k]:v}};assert.equal(run('VERIFY_SITE_CREATE',c).state.tx.status,'pending');}
let read={read:{parentId:parent,parentName:'XDX Parent',limit:5,offset:0,q:'SupplierSiteId>0'},tx:{}};c=ctx('','',{},read);c.$nodes.FETCH_SITES={$output:{items:[{...payload,SupplierSiteId:'300000999'}],count:1,hasMore:true,limit:5,offset:0}};read=run('SHAPE_SITES',c).state;assert.equal(read.read.nextOffset,5);assert.equal(run('PREPARE_SITE',ctx('next site page','next_site',{},read)).state.read.offset,5);c=ctx('','',{},read);c.$nodes.FETCH_SITE_DETAIL={$output:{...payload,SupplierSiteId:'300000999'}};const widget=run('SHAPE_SITE_DETAIL',c).state.widget;assert(widget.includes('SupplierAddressId'));assert(!widget.includes('hasMore'));
console.log('PASS: site parent/address/BU validation, duplicate BU collapse and mismatch rejection, reference-bound approval, field-only edits, stale and changed-parent/reference withholding, exact numeric/boolean body, pending-before-write, persisted relationship comparison, no accepted replay and ordinary paging/detail.');

// Pending reconciliation never permits another POST, even after no match.
{
 const pending={tx:{parentId:parent,parentName:'XDX Parent',requestId:'pending-site',revision:1,status:'pending',payload,referenceAddressId:address,buName:'US1 Business Unit'},read:{}};
 const c=ctx('','',{},pending);c.$nodes.CHECK_SITE_DUPLICATE={$output:{items:[],count:0,hasMore:false,offset:0}};
 assert.equal(run('AUTHORIZE_SITE_WRITE',c).next,'display');
 c.$nodes.CHECK_SITE_DUPLICATE.$output={items:[{SupplierSiteId:'300000999',SupplierSite:payload.SupplierSite}],count:1,hasMore:false,offset:0};assert.equal(run('AUTHORIZE_SITE_WRITE',c).next,'verify');
 c.$nodes.CHECK_SITE_DUPLICATE.$output.hasMore=true;assert.equal(run('AUTHORIZE_SITE_WRITE',c).next,'display');
 assert.equal(run('PREPARE_SITE',ctx('cancel site','cancel_site',{},pending)).state.tx.status,'pending');
 console.log('PASS: pending site reconciliation verifies one exact candidate only; empty/ambiguous outcomes cannot retry or cancel away uncertainty.');
}
